# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane scheme:

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :sync_certs do
    match(
      readonly: is_ci,
      git_url: "https://github.com/videostream/rth-ios-customer-certs",
      git_branch: "[Branch Name]",
      storage_mode: "git",
      type: "appstore",
      app_identifier: "com.routethis.[Prod Target Name]",
      username: "dev@routethis.com",
      generate_apple_certs: false
    )
  end
  lane :beta do
    setup_ci
    match(
      readonly: is_ci,
      git_url: "https://github.com/videostream/rth-ios-customer-certs",
      git_branch: "[Branch Name]",
      storage_mode: "git",
      type: "appstore",
      app_identifier: "com.routethis.[Prod Target Name]",
      username: "dev@routethis.com",
      generate_apple_certs: false
    )
    build_app(
      scheme: "[Scheme Name]",
      export_options:{ 
        manageAppVersionAndBuildNumber: false 
      }
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      apple_id: "[Apple ID]"
    )
  end
end